### PR TITLE
Add functionality to quit button in RcinnerModelSimulator

### PR DESCRIPTION
**Pull request by nikhil3456**
Quit action was not working. So I added functionality to it.
screenshot from 2019-02-02 00-12-41
Please review it.

### CODE REVIEW

**Comment by orensbruli** [comment]
Thank you for your request!
Have you checked if there's something to delete/destroy/close before exiting the application?
Best.

**Comment by nikhil3456** [comment]
Sir, Communicator was not destroyed but same problem was coming when we close application by pressing cross icon on top right. If you could tell where was communicator initialised then the problem could be resolved.

**Comment by orensbruli** [comment]
> Sir, Communicator was not destroyed but same problem was coming when we close application by pressing cross icon on top right. If you could tell where was communicator initialised then the problem could be resolved.

Is there any error or message on the terminal about the comunicator not been destroyed that you can share? I'm not currently working with this piece of software of robocomp so any information you can share will be helpful to try to resolve this.

**Comment by nikhil3456** [comment]
Yes, below message is coming on terminal when closing application by any means.
![screenshot from 2019-02-02 00-49-03](https://user-images.githubusercontent.com/23725396/52144467-68f5f980-2684-11e9-88b3-85cfa6c7682

**Pull request closed without merging**
