### PR TITLE
fixed issue #242

### PR DESCRIPTION
**Pull request by rahulkatiyar19955**
Required changes have been done, which include adding info about the selected interface in Cpp and python template files.

### CODE REVIEW

**Comment by orensbruli** [comment]
Have you tested it generating a new Python and C++ components?

**Comment by rahulkatiyar19955** [comment]
> Have you tested it generating a new Python and C++ components?

Yes, I have tested by creating a new component in both languages Cpp 
as well as in Python, and getting these as the output.
[Generated_Outputs.pdf](https://github.com/robocomp/robocomp/files/4264956/Generated_Outputs.pdf)

**Comment by orensbruli** [comment]
@pbustos can you test if this fixes your #242 issue and we can merge and close the issue?

**Comment by pbustos** [comment]
Thanks rahulkatiyar19955

**Pull request merged**
