### PR TITLE
Added a link to a Doc-Tutorial and a YouTube-Tutorial on how to make a PR using Terminal

### LINKED ISSUE #311: [Newcomers issue] Broken link
### Describe the bug

A link in [first_issue.md](https://github.com/robocomp/robocomp/blob/development/.github/ISSUE_TEMPLATE/first_issue.md) is broken.

### Instructions
This is a ``first-timer-only`` issue. **So the people who have not contributed to robocomp's codebase before, or people who have not contributed to open source before can take this up.**

If you have contributed before, **consider leaving this PR for someone new** :)

The contributor has to replace a broken link
```diff
diff --git a/.github/ISSUE_TEMPLATE/first_issue.md b/.github/ISSUE_TEMPLATE/first_issue.md
index 2a8db59a..d3f54b86 100644
--- a/.github/ISSUE_TEMPLATE/first_issue.md
+++ b/.github/ISSUE_TEMPLATE/first_issue.md
@@ -35,7 +35,7 @@ You do not need to know anything prior to taking up this issue! Welcome to opens
 
 If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow on how GitHub works.](https://guides.github.com/activities/hello-world/)
 
-If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial on how to send a pull request using the terminal.](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github)
+If you are familiar with the terminal or would like to learn to use it, [here is a great tutorial on how to send a pull request using the terminal.](https://github.com/robocomp/robocomp/blob/development/doc/contribute/contribute.md)
 ```
 ### Questions?
 Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below or ask in the [gitter channel](https://gitter.im/robocomp).

#### Prerequisites
You do not need to know anything prior to taking up this issue! Welcome to opensource!
Use this great [tutorial](https://github.com/robocomp/robocomp/blob/development/doc/contribute/contribute.md) if you have never contributed before.

#### 📋 Steps
- [ ] **Claim this issue** : Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ]  **Fork the robocomp/robocomp repository** using the fork button on the topright corner.

- [ ] **Clone the newly forked repository** on your local machine.

- [ ] **Update** the file [first_issue.md](https://github.com/robocomp/robocomp/blob/development/.github/ISSUE_TEMPLATE/first_issue.md) by replacing the broken link with https://github.com/robocomp/robocomp/blob/development/doc/contribute/contribute.md

- [ ] **Commit and push** your changes.

- [ ] **Make a Pull Request** by going to your fork of robocomp.

- [ ] **Ask in comments for a maintainer to review**.

If you are not familiar with GitHub or how to create a pull request, [here is a guide you can follow on how GitHub works.](https://guides.github.com/activities/hello-world/)

### Questions?
Don’t hesitate to ask questions or to get help if you feel like you are getting stuck. For example leave a comment below or ask in the [gitter channel](https://gitter.im/robocomp).

[Robocomp FAQ](https://github.com/robocomp/robocomp/blob/development/doc/FAQ.md)
[Robocomp Tutorials](https://github.com/robocomp/robocomp/blob/development/doc/README.md)
[Robocomp Contribution guide](https://github.com/robocomp/robocomp/blob/development/CONTRIBUTING.md)

**Good luck with your first issue!**

### PR DESCRIPTION
**Pull request by HassanRahim26**
Fixed #311.
I have added a link to a Doc-Tutorial as well as a Youtube-Tutorial on how to make a PR using Terminal.

### CODE REVIEW

**Comment by HassanRahim26** [comment]
Hey, @marcoag sir, @mhaut sir, @nithinmurali sir please review my Pull Request.

**Comment by HassanRahim26** [comment]
Hey, @orensbruli  sir, @pawanw17 I have added the link to a Doc-Tutorial as mentioned. So, please review it.

**Comment by pawanw17** [comment]
Hello @HassanRahim26 this looks good! just a tip : you don't need to make another branch, you can commit and push in the same branch with which you made the PR and the changes will automatically be reflected.

**Comment by HassanRahim26** [comment]
> Hello @HassanRahim26 this looks good! just a tip : you don't need to make another branch, you can commit and push in the same branch with which you made the PR and the changes will automatically be reflected.

Hey @pawanw17, thank you so much for the tip. The next time, I'll be careful about it.

**Comment by HassanRahim26** [comment]
> Hello @HassanRahim26 this looks good! just a tip : you don't need to make another branch, you can commit and push in the same branch with which you made the PR and the changes will automatically be reflected.

Hey @pawanw17, thank you so much for the tip. The next time, I'll be careful about it.

**Comment by HassanRahim26** [comment]
> Hello @HassanRahim26 this looks good! just a tip : you don't need to make another branch, you can commit and push in the same branch with which you made the PR and the changes will automatically be reflected.

Hey @pawanw17, thank you so much for the tip. The next time, I'll be careful.

**Pull request merged**
