### PR TITLE
Remove unwanted comments 'biasedRandomSelector.h'

### PR DESCRIPTION
**Pull request by charanjit-singh**

### CODE REVIEW

**Comment by charanjit-singh** [comment]
I didn't do anything, this project is failing even if you dont do anything

**Comment by charanjit-singh** [comment]
Anyone?

**Comment by orensbruli** [comment]
> I didn't do anything, this project is failing even if you dont do anything

What do you mean?

**Comment by charanjit-singh** [comment]
Tests are failing on travis-ci

**Comment by orensbruli** [comment]
> Tests are failing on travis-ci

We use some features of c++11 and zeroc-ice only has support in its libraries for c++11 from version 3.7. Ice version 3.7 is only available for Ubuntu 18.04 and travis can only run with ubuntu versions prior to 16.04. That's why Travis fails to compile robocomp.

**Comment by orensbruli** [comment]
About your PR, have you checked to see if this library is being used at any point? Or have you just deleted the comments while browsing? 
As it is only to remove comments that seem to have remained from the development I proceed to accept the pull request. Thank you.

**Comment by charanjit-singh** [comment]
I've deleted comments directly from the browser and my system has ubuntu 19.04, and I didn't face any issue while setting up this project.

**Pull request merged**
