### PR TITLE
ICE Demo with OpenCV integration

### PR DESCRIPTION
**Pull request by abhi-kumar**
As instructed by @pbustos here's a simple demo of ICE with a small integration of OpenCV. 

Overview:
This demo introduces the working of Ice cpp platform. The demo working includes a server and a client. The server initiates the process and makes a room for printing relevant data. The client on the other hand passes the printable data to the server and initiates the OpenCV component. The OpenCV component includes a live video-stream from integrated camera of the system and applies two minor utilities of OpenCV, namely, "conversion to grayscale", and "conversion to edge based representation of image".

Note: Currently it is of the built-independent form"

Please have a look at the demo and integrate it with the repository.

Regards,
Abhishek

### CODE REVIEW

**Comment by abhi-kumar** [comment]
Please ignore commit ID - 9e980cc & c6006eb. Just consider ID - 610790a

Regards,
Abhishek

**Comment by abhi-kumar** [comment]
Please let me know if there are any compilation and execution errors associated with this demo

Regards,
Abhishek

**Comment by pbustos** [comment]
Hello, Abhishek,

we create components using the "robocompdsl" code generator in
~/robocomp/tools

There is a short tutorial on it in github

Thanks

Pablo

On Sun, Apr 26, 2015 at 12:54 PM, Abhishek Kumar Annamraju <
notifications@github.com> wrote:

> Please let me know if there are any compilation and execution errors
> associated with this demo
>
> Regards,
> Abhishek
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robocomp/robocomp/pull/43#issuecomment-96364594>.
>



-- 
Pablo Bustos García de Castro
Laboratorio de Robótica y Visión Artificial
http://robolab.unex.es
Escuela Politécnica
Universidad de Extremadura
Avda de la Universidad s/n
Cáceres 10003
Phone: +34 927 257259
Fax: +34 927 257203

**Comment by abhi-kumar** [comment]
@pbustos I will read the tutorial and modify the component.

**Pull request closed without merging**
